"""Small built-in travel knowledge base for the MVP workflow.

The data is intentionally compact. The workflow is designed so these records can
later be replaced with API results from maps, weather, flight, or hotel tools.
"""

DESTINATIONS = {
    "lisbon": {
        "display_name": "Lisbon",
        "country": "Portugal",
        "cost_level": "medium",
        "daily_food_per_person": 45,
        "daily_lodging_total": 135,
        "local_transport_total": 55,
        "flight_estimates": {
            "new york": 900,
            "london": 230,
            "paris": 190,
            "casablanca": 260,
            "madrid": 120,
        },
        "areas": [
            {
                "name": "Baixa / Chiado",
                "fit": "first-time visitors who want central walks and easy transit",
                "tradeoff": "more expensive and busy",
            },
            {
                "name": "Alfama",
                "fit": "history, viewpoints, and atmospheric evenings",
                "tradeoff": "hilly streets and fewer metro options",
            },
            {
                "name": "Principe Real",
                "fit": "restaurants, boutiques, and a quieter base",
                "tradeoff": "slightly farther from some classic sights",
            },
        ],
        "weather_notes": [
            "September is usually warm and dry, with cooler evenings near the river.",
            "Plan sun protection for midday walks and keep flexible indoor options.",
        ],
        "transport_notes": [
            "Metro, trams, buses, and ride-hailing cover most visitor routes.",
            "Avoid renting a car inside Lisbon unless leaving the city for several days.",
        ],
        "must_know": [
            "Book popular restaurants and Sintra day trips ahead in peak months.",
            "Many viewpoints and old districts involve steep walking.",
        ],
        "activities": [
            {
                "name": "Alfama walking route",
                "category": "history",
                "duration_hours": 2.0,
                "best_time": "morning",
                "area": "Alfama",
                "cost": 0,
                "booking_needed": False,
                "priority": 10,
            },
            {
                "name": "Sao Jorge Castle",
                "category": "history",
                "duration_hours": 2.0,
                "best_time": "morning",
                "area": "Alfama",
                "cost": 15,
                "booking_needed": False,
                "priority": 9,
            },
            {
                "name": "Time Out Market lunch",
                "category": "food",
                "duration_hours": 1.5,
                "best_time": "afternoon",
                "area": "Cais do Sodre",
                "cost": 25,
                "booking_needed": False,
                "priority": 8,
            },
            {
                "name": "Belem Tower and riverside walk",
                "category": "history",
                "duration_hours": 2.0,
                "best_time": "morning",
                "area": "Belem",
                "cost": 8,
                "booking_needed": False,
                "priority": 8,
            },
            {
                "name": "Jeronimos Monastery",
                "category": "history",
                "duration_hours": 1.5,
                "best_time": "morning",
                "area": "Belem",
                "cost": 12,
                "booking_needed": True,
                "priority": 9,
            },
            {
                "name": "Pasteis de Belem stop",
                "category": "food",
                "duration_hours": 0.75,
                "best_time": "afternoon",
                "area": "Belem",
                "cost": 8,
                "booking_needed": False,
                "priority": 8,
            },
            {
                "name": "Chiado and Baixa walk",
                "category": "walkable neighborhoods",
                "duration_hours": 2.0,
                "best_time": "afternoon",
                "area": "Baixa / Chiado",
                "cost": 0,
                "booking_needed": False,
                "priority": 8,
            },
            {
                "name": "Fado evening",
                "category": "music",
                "duration_hours": 2.5,
                "best_time": "evening",
                "area": "Alfama",
                "cost": 45,
                "booking_needed": True,
                "priority": 7,
            },
            {
                "name": "LX Factory",
                "category": "food",
                "duration_hours": 2.0,
                "best_time": "afternoon",
                "area": "Alcantara",
                "cost": 15,
                "booking_needed": False,
                "priority": 6,
            },
            {
                "name": "Sintra day trip",
                "category": "history",
                "duration_hours": 7.0,
                "best_time": "full_day",
                "area": "Sintra",
                "cost": 45,
                "booking_needed": True,
                "priority": 8,
            },
        ],
    },
    "marrakech": {
        "display_name": "Marrakech",
        "country": "Morocco",
        "cost_level": "medium-low",
        "daily_food_per_person": 30,
        "daily_lodging_total": 95,
        "local_transport_total": 45,
        "flight_estimates": {
            "new york": 1050,
            "london": 260,
            "paris": 220,
            "casablanca": 80,
            "madrid": 160,
        },
        "areas": [
            {
                "name": "Medina",
                "fit": "first-time visitors who want markets, riads, and historic sights",
                "tradeoff": "busy, maze-like, and less quiet",
            },
            {
                "name": "Gueliz",
                "fit": "modern restaurants, easier taxis, and calmer evenings",
                "tradeoff": "less traditional atmosphere",
            },
        ],
        "weather_notes": [
            "September is often hot during the day and more comfortable at night.",
            "Start outdoor sightseeing early and keep afternoons lighter.",
        ],
        "transport_notes": [
            "Use walking inside the Medina and taxis for longer hops.",
            "Confirm taxi prices before getting in when meters are not used.",
        ],
        "must_know": [
            "Friday hours can affect some shops and local services.",
            "Modest clothing is practical for religious and traditional sites.",
        ],
        "activities": [
            {
                "name": "Medina and souks route",
                "category": "walkable neighborhoods",
                "duration_hours": 3.0,
                "best_time": "morning",
                "area": "Medina",
                "cost": 0,
                "booking_needed": False,
                "priority": 10,
            },
            {
                "name": "Bahia Palace",
                "category": "history",
                "duration_hours": 1.5,
                "best_time": "morning",
                "area": "Medina",
                "cost": 8,
                "booking_needed": False,
                "priority": 9,
            },
            {
                "name": "Jemaa el-Fnaa food walk",
                "category": "food",
                "duration_hours": 2.0,
                "best_time": "evening",
                "area": "Medina",
                "cost": 25,
                "booking_needed": False,
                "priority": 9,
            },
            {
                "name": "Majorelle Garden",
                "category": "art",
                "duration_hours": 1.5,
                "best_time": "morning",
                "area": "Gueliz",
                "cost": 17,
                "booking_needed": True,
                "priority": 8,
            },
            {
                "name": "Cooking class",
                "category": "food",
                "duration_hours": 4.0,
                "best_time": "afternoon",
                "area": "Medina",
                "cost": 55,
                "booking_needed": True,
                "priority": 8,
            },
        ],
    },
}


INTEREST_ALIASES = {
    "food": {"food", "restaurants", "cooking", "market", "markets", "street food"},
    "history": {"history", "museums", "museum", "castle", "castles", "architecture"},
    "walkable neighborhoods": {"walkable", "walking", "neighborhoods", "neighbourhoods"},
    "art": {"art", "design", "galleries", "gallery"},
    "music": {"music", "nightlife", "shows"},
}
